#!/usr/bin/env python3
"""
gen_keys.py — Generate an Ed25519 signing keypair for secure boot.

The private key is stored as a passphrase-encrypted PEM file on disk.
This is the standard approach used by U-Boot and Zephyr for firmware signing.
You can migrate to a hardware token (e.g. YubiKey) later without changing
the bootloader or sign_image.py.

Usage:
    python tools\\gen_keys.py --out tools\\private_key.pem

When prompted, enter a strong passphrase to encrypt the private key.
Store the passphrase securely (password manager, not written down).

Outputs:
  tools/private_key.pem           — passphrase-encrypted private key (KEEP SECRET, NOT in git)
  tools/public_key.bin            — raw 32-byte public key (safe to commit)
  bootloader/src/boot/pubkey.c   — updated with the 32-byte public key
"""

import argparse
import getpass
import os
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT  = SCRIPT_DIR.parent
PUBKEY_C   = REPO_ROOT / "bootloader" / "src" / "boot" / "pubkey.c"
PUBKEY_BIN = SCRIPT_DIR / "public_key.bin"


def write_pubkey_c(pubkey_bytes: bytes, output_path: Path) -> None:
    if len(pubkey_bytes) != 32:
        raise ValueError(f"Expected 32-byte key, got {len(pubkey_bytes)}")
    rows = [
        "  " + ", ".join(f"0x{b:02X}" for b in pubkey_bytes[i:i+8])
        for i in range(0, 32, 8)
    ]
    hex_block = ",\n".join(rows)
    content = (
        '/// @file pubkey.c\n'
        '/// @brief ROM-resident Ed25519 public key for application image verification.\n'
        '///\n'
        '/// Generated by tools/gen_keys.py.  Re-run only when rotating the signing key.\n'
        '/// After rotation: rebuild the bootloader and reflash it, then re-sign the app.\n'
        '\n'
        '#include "pubkey.h"\n'
        '\n'
        'const uint8_t g_rom_pubkey[32] = {\n'
        + hex_block + '\n'
        '};\n'
    )
    output_path.write_text(content, encoding="utf-8")
    print(f"[gen_keys] pubkey.c written: {output_path}")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate an Ed25519 signing keypair for secure boot"
    )
    parser.add_argument("--out", default=str(SCRIPT_DIR / "private_key.pem"),
                        help="Output path for encrypted private key PEM [tools/private_key.pem]")
    args = parser.parse_args()

    try:
        from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
        from cryptography.hazmat.primitives.serialization import (
            Encoding, PrivateFormat, PublicFormat,
            BestAvailableEncryption, NoEncryption,
        )
    except ImportError:
        print("ERROR: cryptography not installed. Run: pip install -r tools/requirements.txt")
        return 1

    out_path = Path(args.out)
    if out_path.exists():
        print(f"ERROR: {out_path} already exists.")
        print("Delete it first if you intend to rotate keys.")
        return 1

    # Prompt for passphrase (twice to confirm)
    passphrase = getpass.getpass("Enter passphrase to encrypt private key: ")
    confirm    = getpass.getpass("Confirm passphrase: ")
    if passphrase != confirm:
        print("ERROR: Passphrases do not match.")
        return 1
    if len(passphrase) < 8:
        print("ERROR: Passphrase must be at least 8 characters.")
        return 1

    # Generate key
    private_key = Ed25519PrivateKey.generate()
    public_key  = private_key.public_key()

    # Serialize private key — encrypted PEM (AES-256-GCM via BestAvailableEncryption)
    enc = BestAvailableEncryption(passphrase.encode())
    pem = private_key.private_bytes(Encoding.PEM, PrivateFormat.PKCS8, enc)
    out_path.write_bytes(pem)
    # Restrict to owner-read-only on platforms that support it
    try:
        os.chmod(out_path, 0o600)
    except OSError:
        pass
    print(f"[gen_keys] Encrypted private key: {out_path}")

    # Export raw 32-byte public key
    pubkey_bytes = public_key.public_bytes(Encoding.Raw, PublicFormat.Raw)
    print(f"[gen_keys] Public key: {pubkey_bytes.hex()}")

    write_pubkey_c(pubkey_bytes, PUBKEY_C)

    PUBKEY_BIN.write_bytes(pubkey_bytes)
    print(f"[gen_keys] Raw public key saved: {PUBKEY_BIN}")

    print()
    print("IMPORTANT: Keep tools/private_key.pem secret and backed up.")
    print("           It is gitignored and must NOT be committed.")
    print()
    print("Next steps:")
    print("  1. Rebuild the bootloader:  .\\build.ps1")
    print("  2. Sign the app image:      python tools\\sign_image.py build\\app\\Release\\App.bin")
    print("  3. Flash both:              .\\flash.ps1")
    return 0


if __name__ == "__main__":
    sys.exit(main())
